---
version: "3.2"
services:
  app:
    build: .
    environment:
        PHP_IDE_CONFIG: 'serverName=olvlvl/attribute-collector'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
